import { ArrowLeft, Download, Mail, ShieldCheck } from 'lucide-react'
import type { ReportSection } from '../lib/anthropic'
import type { Incident } from '../lib/incidents'
import DecisionChart from './DecisionChart'
import OutcomesChart from './OutcomesChart'
import SectionRenderer from './SectionRenderer'

type ReportViewerProps = {
  incident: Incident
  audience: string
  generatedAt: Date
  isLoading: boolean
  error: string | null
  sections: ReportSection[]
  onNewReport: () => void
}

const loadingSections = [
  'EXECUTIVE SUMMARY',
  'EVENT TIMELINE',
  'AUTONOMOUS DECISIONS SUMMARY',
  'HUMAN OVERRIDE LOG',
  'RESOURCE UTILISATION',
  'POPULATION OUTCOMES',
  'MODEL PERFORMANCE',
  'RECOMMENDATIONS',
]

function formatGeneratedAt(date: Date) {
  const parts = new Intl.DateTimeFormat('en-GB', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    hour12: false,
    timeZone: 'Asia/Kolkata',
  }).formatToParts(date)

  const lookup = Object.fromEntries(parts.map((part) => [part.type, part.value]))
  return `${lookup.day} ${lookup.month} ${lookup.year}, ${lookup.hour}:${lookup.minute} IST`
}

export default function ReportViewer({
  incident,
  audience,
  generatedAt,
  isLoading,
  error,
  sections,
  onNewReport,
}: ReportViewerProps) {
  return (
    <main className="viewer-page">
      <header className="report-header">
        <div className="report-header-inner">
          <p>DISASTERMIND // POST-INCIDENT ANALYSIS REPORT</p>
          <h1>
            {incident.disaster} - {incident.location} | {incident.month} | CLASSIFICATION: OFFICIAL
          </h1>
          <span>
            Generated: {formatGeneratedAt(generatedAt)} | Audience: {audience}
          </span>
        </div>
      </header>

      <article className="document-sheet">
        {isLoading ? (
          <LoadingReport />
        ) : (
          <>
            {error && (
              <div className="fallback-notice">
                <ShieldCheck size={18} />
                <span>{error}</span>
              </div>
            )}
            {sections.map((section, index) => (
              <div key={section.title}>
                <SectionRenderer section={section} />
                {index === 2 && <DecisionChart />}
                {index === 4 && (
                  <OutcomesChart atRisk={incident.civiliansAtRisk} reached={incident.civiliansReached} />
                )}
              </div>
            ))}
            <footer className="report-footer">
              <p>This report was generated by DisasterMind AI v1.0</p>
              <p>All autonomous decisions are logged in the tamper-proof audit trail.</p>
              <p>For queries: ndma-disastermind@gov.in</p>
            </footer>
          </>
        )}
      </article>

      <nav className="action-bar" aria-label="Report actions">
        <button type="button">
          <Download size={18} />
          DOWNLOAD PDF
        </button>
        <button type="button">
          <Mail size={18} />
          SEND TO NDMA
        </button>
        <button onClick={onNewReport} type="button">
          <ArrowLeft size={18} />
          NEW REPORT
        </button>
      </nav>
    </main>
  )
}

function LoadingReport() {
  return (
    <section className="loading-report">
      <div className="loading-copy">
        <h2>DisasterMind AI synthesising incident data...</h2>
        <p>Compiling audit trail, field decisions, resource telemetry, and population outcome metrics.</p>
      </div>
      <div className="progress-bar">
        <div />
      </div>
      <div className="loading-sections">
        {loadingSections.map((section, index) => (
          <div className="loading-section" key={section} style={{ animationDelay: `${index * 0.18}s` }}>
            <strong>{section}</strong>
            <span />
          </div>
        ))}
      </div>
    </section>
  )
}
