-- DisasterMind backend schema (PRD Step 9 persistence, Step 6 telemetry).
-- Generated by disastermind.integrations.sql.schema_sql(); do not edit by hand.
-- PostGIS resource store (dm_assets, dm_zones) + TimescaleDB hypertable (dm_telemetry).
CREATE EXTENSION IF NOT EXISTS postgis;

CREATE EXTENSION IF NOT EXISTS timescaledb;

CREATE TABLE IF NOT EXISTS dm_assets (
    asset_id   TEXT PRIMARY KEY,
    type       TEXT NOT NULL,
    lat        DOUBLE PRECISION NOT NULL,
    lon        DOUBLE PRECISION NOT NULL,
    capacity   INTEGER NOT NULL DEFAULT 0,
    available  BOOLEAN NOT NULL DEFAULT TRUE,
    fuel_pct   DOUBLE PRECISION NOT NULL DEFAULT 100.0,
    geom       GEOMETRY(Point, 4326)
);

CREATE INDEX IF NOT EXISTS dm_assets_geom_idx ON dm_assets USING GIST (geom);

CREATE TABLE IF NOT EXISTS dm_zones (
    cell_id                      TEXT PRIMARY KEY,
    lat                          DOUBLE PRECISION NOT NULL,
    lon                          DOUBLE PRECISION NOT NULL,
    population                   INTEGER NOT NULL DEFAULT 0,
    elderly_density              DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    hospital_proximity           DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    road_accessibility           DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    informal_settlement_density  DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    mobility_impaired            INTEGER NOT NULL DEFAULT 0,
    children                     INTEGER NOT NULL DEFAULT 0,
    hospitalised                 INTEGER NOT NULL DEFAULT 0,
    geom                         GEOMETRY(Point, 4326)
);

CREATE INDEX IF NOT EXISTS dm_zones_geom_idx ON dm_zones USING GIST (geom);

CREATE TABLE IF NOT EXISTS dm_telemetry (
    sensor_id  TEXT NOT NULL,
    metric     TEXT NOT NULL,
    value      DOUBLE PRECISION NOT NULL,
    ts         TIMESTAMPTZ NOT NULL,
    meta       JSONB NOT NULL DEFAULT '{}'::jsonb
);

SELECT create_hypertable('dm_telemetry', 'ts', if_not_exists => TRUE);

CREATE INDEX IF NOT EXISTS dm_telemetry_sensor_metric_ts_idx ON dm_telemetry (sensor_id, metric, ts DESC);
